# Site settings
title: Insomniacs Documentation
email: vigneshv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the FRC Team 2489 Documentation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  vigneshv59

# Build settings
markdown: kramdown
